pandas
matplotlib
seaborn
plotly
streamlit



# -*- coding: utf-8 -*-
"""Copia de Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12gi2-BKgaD19UMNcKJmNY44oUcNmY5t-
"""

#Cargamos librerias

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cargamos el archivo CSV
df = pd.read_csv("university_student_data.csv")

# Para ver las primeras filas
df.head()

# Información general
df.info()

# Estadísticas básicas
df.describe()

# Columnas
df.columns

#para ver los nombres de las columnas
df.columns

#Grafica Retention rate trends over time
plt.figure(figsize=(8,5))
sns.lineplot(data=df, x="Year", y="Retention Rate (%)", marker="o")
plt.title("Retention Rate Trends Over Time")
plt.ylabel("Retention Rate (%)")
plt.show()

#Grafica student satisfaction scores by year
plt.figure(figsize=(8,5))
sns.barplot(data=df, x="Year", y="Student Satisfaction (%)", palette="coolwarm")
plt.title("Student Satisfaction by Year")
plt.ylabel("Average Satisfaction (%)")
plt.xlabel("Year")
plt.show()

#Grafica Comparison between Spring and Fall terms
plt.figure(figsize=(8,5))
sns.boxplot(data=df, x="Term", y="Retention Rate (%)", palette="Set2")
plt.title("Retention Rate Comparison: Spring vs Fall")
plt.ylabel("Retention Rate (%)")
plt.xlabel("Term")
plt.show()

#Agrupacion de datos para anlisis
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
df["Retention Rate (%)"] = df["Retention Rate (%)"].astype(str).str.replace('%','', regex=False).astype(float)
df["Student Satisfaction (%)"] = df["Student Satisfaction (%)"].astype(str).str.replace('%','', regex=False).astype(float)


retention_year = df.groupby("Year")["Retention Rate (%)"].mean().reset_index()
satisfaction_year = df.groupby("Year")["Student Satisfaction (%)"].mean().reset_index()
term_comparison = df.groupby("Term")["Retention Rate (%)"].mean().reset_index()

# Mostrar resultados
print(retention_year.head())
print(satisfaction_year.head())
print(term_comparison.head())
